# TODO: make this production ready
# base image
FROM python:3.9.16 

# env
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONBUFFERED 1

# install system dependencies
RUN apt-get update \
  && apt-get -y install netcat gcc postgresql \
  && apt-get clean

# install python dependencies
RUN pip install --upgrade pip
COPY api/.devcontainer/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# install python tools
COPY common/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# start the server
CMD ["uvicorn", "app.fastapi_server:app", "--host", "0.0.0.0", "--port", "8001"]