version: '3'

services:
  api:
    env_file:
      - ../../../.env
    build:
      context: ../../
      dockerfile: api/.devcontainer/Dockerfile
    volumes:
      # Mount the root folder that contains .git
      - ../../..:/workspace:cached
    ports:
      - "8000:8000"
    command: bash -c "uvicorn src.fastapi_server:app --reload --workers 1 --host 0.0.0.0 --port 8000 --log-level debug"

    networks:
      api-net:
        ipv4_address: 192.168.0.4

networks:
  api-net:
    ipam:
      driver: default 
      config:
      - subnet: "192.168.0.0/24"  #ipv4
        gateway: 192.168.0.1