# train params
batch_size:
  default: 16
  description: batch size per device

num_epochs:
  default: 5
  description: number of epochs to train for

# model params
model_name:
  default: resnet34
  description: model name 

pretrained:
  default: True
  description: use pretrained model from timm, if config given use that

num_classes:
  default: null
  description: number of classes in dataset

in_chans:
  default: 3
  description: number of input channels

drop_rate:
  default: 0.0
  description: dropout rate

drop_path_rate:
  default: null
  description: drop path rate

drop_block_rate:
  default: null
  description: drop block rate

global_pool:
  default: null
  description: global pool type, one of (fast, avg, max, avgmax, avgmaxc). Model default if None

bn_momentum:
  default: null
  description: batch norm momentum

bn_eps:
  default: null
  description: batch norm epsilon

scriptable:
  default: False
  description: make model torchscriptable

checkpoint_path:
  default: null
  description: path to checkpoint to load

# mixup params
mixup_alpha:
  default: 0.2
  description: mixup alpha

mixup_prob:
  default: 1
  description: probability of applying mixup

cutmix_alpha:
  default: 0.0
  description: cutmix alpha

smoothing:
  default: 0.1
  description: label smoothing

# optimizer params
opt:
  default: sgd
  description: optimizer name

lr:
  default: 0.01
  description: learning rate

weight_decay:
  default: 0.00002
  description: weight decay

momentum:
  default: 0.9
  description: momentum

# scheduler params
sched:
  default: cosine
  description: learning rate scheduler name

grad_accum_steps:
  default: 1
  description: gradient accumulation steps

# distributed learning params
