version: '3'

services:
  sample_cpu_project:
    env_file:
      - ../../../.env
    build:
      context: ../../
      dockerfile: sample_cpu_project/.devcontainer/Dockerfile
    volumes:
      # Mount the root folder that contains .git
      - ../../..:/workspace:cached
      # Mount data folder
      - ../../../data:/workspace/src/sample_cpu_project/src/data:cached 
    
    command: /bin/sh -c "while sleep 1000; do :; done"
